name: stream_rate
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  barcode: ^2.2.8
  camera: ^0.10.5+5
  carousel_slider: ^5.0.0
  device_preview: ^1.1.0
  dots_indicator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  google_fonts: ^4.0.4
  permission_handler: ^11.0.1
  pin_code_fields: ^8.0.1
  provider: ^6.1.2
  shared_preferences: any
  slider_captcha: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/onboarding/
    - assets/gifs/
    - assets/svgs/
    - assets/images/splash/