name: stream_rate
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  carousel_slider: ^5.0.0
  dots_indicator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  google_fonts: ^4.0.4
  shared_preferences: any
  slider_captcha: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/images/
    - assets/gifs/
    - assets/svgs/